Execution Result for model_h2o_training.py
--------------------------------------------------
=== Execution successful (attempt 1/3) in 98.26s ===
LOG_START:DATA_SUMMARY
{"n_rows": 504, "n_cols": 2, "dtypes": {"fecha": "object", "monto total": "float64"}, "n_nulls": {"fecha": 0, "monto total": 0}, "sample": [{"fecha": "15 nov. 2023", "monto total": 8992.62}, {"fecha": "16 nov. 2023", "monto total": 1354.86}, {"fecha": "21 nov. 2023", "monto total": 15071.95}]}
LOG_END:DATA_SUMMARY
LOG_START:DATE_FEATURES_CREATED
Column:fecha
Features created: year, month, day, dayofweek, etc.
LOG_END:DATE_FEATURES_CREATED
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "21.0.8" 2025-07-15; OpenJDK Runtime Environment (build 21.0.8+9-Debian-1); OpenJDK 64-Bit Server VM (build 21.0.8+9-Debian-1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpuzgfwa9a
  JVM stdout: /tmp/tmpuzgfwa9a/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpuzgfwa9a/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is (5 months and 9 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html
--------------------------  ----------------------------------
H2O_cluster_uptime:         00 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    5 months and 9 days
H2O_cluster_name:           H2O_from_python_unknownUser_f5kkzs
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.984 Gb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.11.13 final
--------------------------  ----------------------------------
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
LOG_START:FEATURES_SELECTED
Target: monto total
Features: ['fecha', 'fecha__year', 'fecha__month', 'fecha__day', 'fecha__dayofweek', 'fecha__dayofyear', 'fecha__week', 'fecha__quarter', 'fecha__is_weekend', 'fecha__is_month_start', 'fecha__is_month_end', 'fecha__lag1', 'fecha__lag7', 'fecha__rolling_mean7']
Total features: 14
LOG_END:FEATURES_SELECTED
AutoML progress: |
16:00:37.81: User specified a validation frame with cross-validation still enabled. Please note that the models will still be validated using cross-validation only, the validation frame will be used to provide purely informative validation metrics on the trained models.

██████████████████████████████████████████████████████████████████| (done) 100%
MODEL_PATH_START:/workspace/pipeline_fe7ccf65-e073-4c98-ba7d-6740e42a87cf/GBM_grid_1_AutoML_1_20250905_160037_model_1:MODEL_PATH_END
METRICS_START:{"model_path": "/workspace/pipeline_fe7ccf65-e073-4c98-ba7d-6740e42a87cf/GBM_grid_1_AutoML_1_20250905_160037_model_1", "mojo_path": "/workspace/pipeline_fe7ccf65-e073-4c98-ba7d-6740e42a87cf/GBM_grid_1_AutoML_1_20250905_160037_model_1.zip", "metrics": {"rmse": 103853.47360120754, "mae": 78515.0507054444, "r2": 0.6278447205279177, "mse": 10785543979.036713}, "rows_trained": 504, "n_cols": 15, "training_time_secs": 95.59844517707825, "seed": 42, "h2o_version": "3.46.0.7"}:METRICS_END
H2O session _sid_957e closed.
